### ISSUE TITLE
Connector loses subscription after running for a while

### ISSUE THREAD

**Issue by sharafian** [interledgerjs/ilp-connector#304]
```
[api] 2017-02-01T13:46:10.970Z http INFO   <-- POST /payments/quote
[api] 2017-02-01T13:46:10.984Z sequelize DEBUG Executing (default): SELECT "id", "username", "email", "email_verified", "github_id", "profile_picture", "name", "phone", "address1", "address2", "city", "region", "country", "zip_code", "created_at", "updated_at" FROM "Users" AS "User" WHERE "User"."username" = 'admin' LIMIT 1;
[ledger] 2017-02-01T13:46:11.019Z ledger:koa info <-- GET /accounts/admin
[ledger] 2017-02-01T13:46:11.037Z ledger:koa info --> GET /accounts/admin 200 18ms 221B                            [api] webfinger account
[api] 2017-02-01T13:46:12.238Z connector:route-broadcaster info broadcasting 1 routes to peer.K1wXH.eur.m42g9E5T1P6HPSJKc-UAmGrUuqyUtZEwxa8bWEbyrFo
[api] 2017-02-01T13:46:12.238Z ilp-plugin-virtual:rpc debug calling send_message with [ { ledger: 'peer.K1wXH.eur.',
[api]     account: 'peer.K1wXH.eur.KRixgcBCBdyQln7IBYiopjuNO78QSFtXgOwP1sbsCSk',                                   [api]     data: { method: 'broadcast_routes', data: [Object] } } ]
[api] 2017-02-01T13:46:12.494Z ilp-kit:spsp debug created a sender object
[api] 2017-02-01T13:46:12.500Z ilp-core debug remote quote connector=us.usd.cornelius.sharafian query {"source_address":"us.usd.cornelius.admin","destination_address":"eu.eur.pineapplesheep.admi ","destination_amount":"0.02"}
[ledger] 2017-02-01T13:46:12.531Z ledger:koa info <-- POST /messages                                               [ledger] 2017-02-01T13:46:12.541Z ledger:error-handler warn No Subscriptions: Destination account could not be reached
[ledger] 2017-02-01T13:46:12.542Z ledger:koa info --> POST /messages 422 11ms 82B
[api] 2017-02-01T13:46:12.546Z ilp-core debug getQuote: ignoring remote quote error: Destination account could not be reached
[api] 2017-02-01T13:46:12.547Z ilp:sender debug got destination amount quote response undefined
[api] Error: Got empty quote response from the connector
[api]     at client.connect.then.then (/home/sharafian/ilp-kit/node_modules/ilp/src/lib/sender.js:82:17)           
[api]     at process._tickCallback (internal/process/next_tick.js:103:7)
[api] 2017-02-01T13:46:12.549Z error-handler WARN Not Found: No quote for a specified destination/amount has been found
[api] 2017-02-01T13:46:12.557Z http INFO   --> POST /payments/quote 404 1,586ms -
```

I don't know whether this is the connector's fault or the plugin's fault, but the connector appears to lose its subscription to the ledger. Maybe plugin bells lost the connection and the connector doesn't have a way to reconnect it?

**Comment by justmoon** [comment]
We were seeing some missed notifications at Construct 2017 as well...

There is still a bug in the websocket notification system somewhere.
