### ISSUE TITLE
Removing remote payment channel still break plugins

### ISSUE THREAD

**Issue by kruisdraad** [interledgerjs/ilp-connector#450]
Condition: You have a working client/server peering relation with a remote party. The remote party then removes the paymentchannel on their side. Once down the peering goes down, but the moneyd admin port is still available.

When you restart the connector, the routing seems to startup find (except the broken peer obviously) however it seems to be stuck on bring that peer online. It will report an error like:

debug Error processing BTP packet of type 6: Error: paychan initialization has not completed or has failed.

This still is fine, but after the restart you do not have the admin port listening on port 7769 anymore. The admin gui is one of the few tools that makes it easy to actually trouble shoot these kind of issues. It should always be able to start, even is a single peer misbehaves.

Tempting it would be that if a node is very well connected (lets say every node out there) and then wipes all its payment channels ... all the nodes start misbehaving/getting issues creating a cascading event. We have seen this with individual peerings gone wrong, but on a large scale it might interfere with the stability of the network?

**Comment by adrianhopebailie** [comment]
@kruisdraad I think the issue of admin API not working if there are broken plugins has been resolved. Are you still seeing this occurring?

**Comment by treisto** [comment]
@adrianhopebailie 

Can' access GUI - in browser 127.0.0.1:7700, i get "not found". 
CONNECTOR_ADMIN_API true
CONNECTOR_ADMIN_API_PORT: 7700
Log messages in connector about BTP packet of type 6: Error: paychan initialization has not completed or has failed. How can I erase the connector "cache", so that it restarts fresh? I am using pm2 as in your post here:
https://medium.com/interledger-blog/connector-operations-a1aa4cc6137a
~/ilp-connector$ pm2 restart ecosystem.config.js --update-env
I run 2 connectors https://github.com/interledgerjs/ilp-connector,  which connect to a standalone rippled validator.

**ecosystem.config.js for connector2**
==============================
'use strict'
const path = require('path')

const address = 'rLR52VyyyyyyyyyyyyyyyKnYoYyPoJJgy' 
const secret = 'ssrnzXKyyyyyyyyyyyyyyyyyyySLWHN3D5HM'       

const peer1 = {
    relation: 'peer',
    plugin: 'ilp-plugin-xrp-paychan', //peer with other connector/node over XRP
    assetCode: 'XRP',
    assetScale: 9,
    balance: {
        maximum: '1000000000',
        settleThreshold: '-5000000000',
        settleTo: '0'
    },
    options: {
       server: 'btp+ws://lucnnnnnnnnnnnnnnnu:2afe5e6cece84ed0027ggggggggggggggd6f1c9f3e1b0e43c13ff1ae2ea@192.168.1.146:10666',      
        rippledServer: 'ws://192.168.1.98:51233',     
        peerAddress: 'rMqUT7uGs6Sz1m9vFr7o85XJ3WDAvgzWmj',  
        address,
        secret
     }
}

const ilspServer = {
    relation: 'child',
    plugin: 'ilp-plugin-xrp-asym-server',                   
    assetCode: 'XRP',
    assetScale: 6,
    options: {
        port: 7443,                                           
        xrpServer: 'ws://192.168.1.98:51233',       
        address,
        secret
    }
}

const connectorApp = {
    name: 'connector',
    env: {
        DEBUG: 'ilp*,connector*',
        CONNECTOR_ENV: 'production',
        CONNECTOR_ADMIN_API: true,
        CONNECTOR_ADMIN_API_PORT: 7700,
        CONNECTOR_ILP_ADDRESS: 'private.classictwo',   
        CONNECTOR_BACKEND: 'one-to-one',
        CONNECTOR_SPREAD: '0',
        CONNECTOR_STORE: 'ilp-store-redis',
        CONNECTOR_STORE_CONFIG: JSON.stringify({
            prefix: 'connector',
            port: 6379
        }),
        CONNECTOR_ACCOUNTS: JSON.stringify({
            rust_conn: peer1,       
            ilsp: ilspServer,
        })
    },
    script: path.resolve(__dirname, 'src/index.js')
}

module.exports = { apps: [ connectorApp ] }
=================**Connector 2 log**===========================
2019-03-08T12:35:22.779Z connector:route-broadcaster warn not sending/receiving routes for peer, set sendRoutes/receiveRoutes to override. accountId=ilsp
2019-03-08T12:35:22.789Z connector:ilp-prepare:trace debug handling ilp prepare. sourceAccount=ilsp destination=peer.config amount=0 condition=Zmh6rfhivXdsj8GLjp+OIAiXFIVu4jOzkCpZHQ1fKSU= expiry=2019-03-08T12:36:22.784Z packet=DEYAAAAAAAAAADIwMTkwMzA4MTIzNjIyNzg0Zmh6rfhivXdsj8GLjp+OIAiXFIVu4jOzkCpZHQ1fKSULcGVlci5jb25maWcA
2019-03-08T12:35:22.789Z connector:ildcp-host:trace debug responding to ILDCP config request. clientAddress=private.classictwo.ilsp
2019-03-08T12:35:22.792Z ilp-protocol-ildcp debug received client info. clientAddress=private.classictwo.ilsp assetScale=6 assetCode=XRP
2019-03-08T12:35:22.816Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug connected to server
2019-03-08T12:35:22.817Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug sending btp packet. type=TYPE_MESSAGE requestId=1165821295 info=auth=;auth_username=luciantrestioreanu;auth_token=2afe5e6cece84ed0027f9a2463edfa6358901bd6f1c9f3e1b0e43c13ff1ae2ea
2019-03-08T12:35:22.827Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug received btp packet. type=TYPE_RESPONSE requestId=1165821295 info=
2019-03-08T12:35:22.828Z connector:ilp-plugin-xrp-paychan[rust_conn] info connecting to rippled
2019-03-08T12:35:22.851Z connector:ilp-plugin-xrp-paychan[rust_conn] info connected to rippled
2019-03-08T12:35:22.854Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug loaded incoming claim: { amount: '0' }
2019-03-08T12:35:22.866Z connector:route-broadcaster:trace debug add peer. accountId=rust_conn sendRoutes=true receiveRoutes=true
2019-03-08T12:35:22.870Z connector:route-broadcaster:trace debug reload local and configured routes.
2019-03-08T12:35:22.872Z connector:app info connector ready (republic attitude). address=private.classictwo version=22.2.0
2019-03-08T12:35:22.872Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug sending btp packet. type=TYPE_MESSAGE requestId=443776296 info=ilp-prepare
2019-03-08T12:35:22.934Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug received btp packet. type=TYPE_ERROR requestId=443776296 info=
2019-03-08T12:35:22.983Z connector:ccp-receiver[rust_conn] debug failed to set route control information on peer. error=Error: {"code":"F00","name":"Error","triggeredAt":"2019-03-08T12:35:50.717Z","data":"{\"message\":\"paychan initialization has not completed or has failed.\"}","protocolData":[]}
    at PluginXrpPaychan.callback (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/src/index.ts:643:20)
    at PluginXrpPaychan.listener (/home/lucian/ilp-connector/node_modules/eventemitter2/lib/eventemitter2.js:290:17)
    at PluginXrpPaychan.EventEmitter.emit (/home/lucian/ilp-connector/node_modules/eventemitter2/lib/eventemitter2.js:357:19)
    at PluginXrpPaychan._handleIncomingBtpPacket (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/src/index.ts:688:14)
    at PluginXrpPaychan._handleIncomingWsMessage (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/src/index.ts:505:18)
    at WebSocketReconnector.EventEmitter.emit (/home/lucian/ilp-connector/node_modules/eventemitter2/lib/eventemitter2.js:354:19)
    at WebSocket._instance.on (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/src/ws-reconnect.ts:120:70)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/node_modules/ws/lib/websocket.js:744:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/node_modules/ws/lib/receiver.js:408:14)
    at Receiver.getData (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/node_modules/ws/lib/receiver.js:347:17)
    at Receiver.startLoop (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/node_modules/ws/lib/receiver.js:133:22)
    at Receiver._write (/home/lucian/ilp-connector/node_modules/ilp-plugin-btp/node_modules/ws/lib/receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
2019-03-08T12:35:27.253Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug received btp packet. type=TYPE_MESSAGE requestId=4087661332 info=ilp-prepare
2019-03-08T12:35:27.254Z connector:ilp-plugin-xrp-paychan[rust_conn] debug querying peer for incoming channel id
2019-03-08T12:35:27.255Z connector:ilp-plugin-xrp-paychan[rust_conn]:trace debug sending btp packet. type=TYPE_MESSAGE requestId=649190879 info=ripple_channel_id=9B8ADB0884B8DC064E1E1E5B2B40FB78AE5546A9B4A82AEA81FC36FF999C6705

**Comment by treisto** [comment]
I have renamed sudo mv /var/lib/redis/dump.rdb /var/lib/redis/dump.rdb.old and changed store to "memdown" ans still get the error.
